### PR TITLE
Update Gradle and remove unnecessary annotations

### PR DESCRIPTION
**Pull request by msfjarvis**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Bump?

**Comment by sfan5** [comment]
The PR is appreciated, note that we usually update Gradle infrequently.

**Comment by msfjarvis** [comment]
> The PR is appreciated, note that we usually update Gradle infrequently.

Any particular reason for that? I find keeping up with Gradle upgrades to be quite helpful as they often include build speed improvements and heaven knows Android needs those.

**Comment by sfan5** [comment]
Potentially lots of useless changes in git, build time is fast enough anyway.
Past gradle updates have been because the Android toolchain required something newer or when a new JRE/JDK came out and Gradle wouldn't run anymore.

**Pull request merged**
