### PR TITLE
New Player UI

### PR DESCRIPTION
**Pull request by m1s4k1**
new_layout

### CODE REVIEW

**Comment by sfan5** [comment]
I know Android Studio might have nagged you about this, but please don't apply code style changes or "upgrade" the gradle files.
It makes it hard to review the actual changes.

**Comment by m1s4k1** [comment]
@sfan5 oh sorry about that. Can you please try to build this? I can't build it for some reason.
If it builds and maybe works I'll rebase it without Kotlin DSL then.

**Comment by sfan5** [comment]
Well, travis had no problem automatically building your PR: https://travis-ci.org/mpv-android/mpv-android/builds/570250828#L1610

**Comment by Pentaphon** [comment]
Looks nice, @m1s4k1 Does it show the current time when scrubbing the progress bar?

**Comment by m1s4k1** [comment]
@Pentaphon thanks. Currently we have the "playback position" (near play button) so I think it's kinda redundant. But maybe I'll do this too.

**Comment by Pentaphon** [comment]
@m1s4k1 yeah the playback position is there but it is kind of small so putting a nice large position counter in the center of the screen when scrubbing would be nice, especially on a small screen like a phone, and it will definitely be useful for gestures like tapping one side of the screen to go back and forth 10 seconds, or dragging your finger from one side of the screen to another to make a larger jump. The progress bar would only be for people who make huge jumps like starting a video again and going back to the middle of the movie where they left off.

**Comment by sfan5** [comment]
Note that there are two buttons that only appear when you actually open a playlist.
These seem to be missing from your UI currently.
screenshot_20171208-233157

**Comment by m1s4k1** [comment]
Any bottom button can be hidden and other buttons will be centered.
In my opinion it's the best place for playlist buttons. If you have any ideas how to improve the UI I'd like to see them.

**Comment by Pentaphon** [comment]
Any test builds with this new UI so people can test with their devices?

**Comment by m1s4k1** [comment]
@Pentaphon It doesn't work for now :(
By the way, I hope I get a chance to work on the new UI in near future so I'll open a new PR when all things will be ready.

**Pull request closed without merging**
