### PR TITLE
Added an intent filter for streaming URL schemes

### PR DESCRIPTION
**Pull request by andrew-shulgin**
Added intent filter for `rtmp`, `rtmpe`, `rtmps`, `rtp`, `rtsp`, `mms`, `mmst`, `mmsh`, and `udp` protocols.
This allows URLs with these protocols to be open directly in MPV.

### CODE REVIEW

**Comment by sfan5** [comment]
fixes #36 btw

are `udp://` URLs ever encountered in the wild?

**Comment by andrew-shulgin** [comment]
Not sure about `udp://`, but mpv should handle it. Why not?

**Comment by andrew-shulgin** [comment]
Just tested opening a multicast `udp://` URL with intent filter. It works.

**Comment by andrew-shulgin** [comment]
UDP streaming is mostly used in IPTV.

**Comment by jeeb** [comment]
Generally LGTM, will be testing as I get a new build going.

**Pull request merged**
