### PR TITLE
feat: Add themed/monochrome icon 

### LINKED ISSUE #973: Material You Icon
It would be great if the mpv icon could be themed with Material You, as it would help it to blend in with the rest of my setup (and, no doubt, other people's setups also).

### PR DESCRIPTION
**Pull request by khaled-0**
image

Slight variation of: https://github.com/LawnchairLauncher/lawnicons/blob/develop/svgs/mpv_android.svg
 (close #973 )

### CODE REVIEW

**Comment by sfan5** [comment]
How is that file licensed? Same as mpv-symbolic.svg since it's a derivative I assume.

**Comment by khaled-0** [comment]
> How is that file licensed? Same as mpv-symbolic.svg since it's a derivative I assume.
It's Apache 2.0

holup, I didn't see that file.
Does it look better or worse? Better imo
image

**Comment by sfan5** [comment]
I would prefer mpv-symbolic since it's an official part of mpv.

**Comment by khaled-0** [comment]
> I would prefer mpv-symbolic since it's an official part of mpv.

agree, done

**Comment by sfan5** [comment]
Thanks.

**Pull request merged**
