### PR TITLE
initial fastlane support

### PR DESCRIPTION
**Pull request by IzzySoft**
Aw, you've updated the description and I almost missed it! That shouldn't happen again, right? :smile: Hence: Fastlane. You can use that to deploy to Play Store as well (might need the Fastlane binaries, though, for that). Then you can maintain your metadata in one place – and use it for many. My updater would pick updated details with each new release. You might even wish to add more (like screenshots, a featureGraphic, per-release changelogs – [my fastlane cheat-sheet](https://gitlab.com/snippets/1895688) can guide you with that); just let me know when you do so, so I can tell my updater what to look for :wink:

Oh, and maybe you might wish to replace the F-Droid badge [with this one](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to avoid confusion?

### CODE REVIEW

**Comment by sfan5** [comment]
By "description" are you referring to the README? I don't remember updating any description(s) on Google Play.

> Oh, and maybe you might wish to replace the F-Droid badge [with this one](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to avoid confusion?

Yes, that'd be a good idea.

**Comment by IzzySoft** [comment]
> By "description" are you referring to the README?

Yes. And by having that in Fastlane (which is what this PR is about), changes made by you would be pulled automatically with the release.

**Comment by IzzySoft** [comment]
@sfan5 any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by sfan5** [comment]
Sorry, I don't think fastlane is currently useful for mpv-android, the description changes very rarely.
I have updated the badge in the README though.

**Comment by IzzySoft** [comment]
Thanks @sfan5 – if it rarely changes, does it hurt having it? For us maintainers it's good so we can rely on those knowing about (potential) changes keeping the description updated. With almost 700 apps in my repo and over 3.000 at F-Droid, it's otherwise hard to make sure. But yes, up to you :wink:

**Comment by linsui** [comment]
Please merge this. Even though the description itself changes very rarely, users can help translate the descriptions. Thanks!

**Comment by IzzySoft** [comment]
Thanks @sfan5! I still wonder why you didn't like the 2 German files, though :smile:

**Pull request closed without merging**
