### PR TITLE
Automatic orientation depending on video aspect ratio

### PR DESCRIPTION
**Pull request by sfan5**
perhaps the most requested feature in play store reviews

### CODE REVIEW

**Comment by sfan5** [comment]
You mean instead of the `Force (Landscape|Portrait)` options?
Since IMO the auto mode is the most useful part of this feature.

**Comment by sfan5** [comment]
When using a setting other than "Automatic", this thingy will appear and do exactly what it looks like:
screen

**Comment by xyzz** [comment]
Okay this looks very good but is there any reason not to show the button all the time?

**Comment by sfan5** [comment]
Making sure the automatic mode does (or doesn't) do its thing when the user can also manually change the orientation is somewhat annoying due to events. Which is why I haven't bothered.

**Pull request merged**
